In [1]:
import numpy as np
import pandas as pd

## Réflechissons un peu

In [3]:
un_panda_numpy = np.array([100, 5, 20, 80])
un_panda_numpy

array([100,   5,  20,  80])

In [5]:
### Si je veux une famille de pandas ?
famille_panda = [
    np.array([100, 5, 20, 80]), # maman panda
    np.array([50, 2.5, 10, 40]), # bébé panda
    np.array([110, 6, 22, 80]) # papa panda
]

In [6]:
famille_panda = [
    [100, 5  , 20, 80], # maman panda
    [50 , 2.5, 10, 40], # bébé panda
    [110, 6  , 22, 80], # papa panda
]
famille_panda_numpy = np.array(famille_panda)
famille_panda_numpy

array([[100. ,   5. ,  20. ,  80. ],
       [ 50. ,   2.5,  10. ,  40. ],
       [110. ,   6. ,  22. ,  80. ]])

In [7]:
famille_panda_numpy[2, 0] # taille des pattes de papa panda, à la manière numpy

110.0

In [8]:
famille_panda_numpy[:, 0]

array([100.,  50., 110.])

## La librairie Pandas

In [9]:
famille_panda_df = pd.DataFrame(famille_panda)
famille_panda_df

0    1   2   3
0  100  5.0  20  80
1   50  2.5  10  40
2  110  6.0  22  80

In [11]:
famille_panda_df = pd.DataFrame(famille_panda_numpy, index = ['maman', 'bebe','papa'], columns = ['pattes', 'poil', 'queue','ventre'])
famille_panda_df

pattes  poil  queue  ventre
maman   100.0   5.0   20.0    80.0
bebe     50.0   2.5   10.0    40.0
papa    110.0   6.0   22.0    80.0

### Quelques fonctionnalités des DataFrames

In [13]:
famille_panda_df.ventre
# ou
famille_panda_df["ventre"]

maman    80.0
bebe     40.0
papa     80.0
Name: ventre, dtype: float64

In [14]:
for idx, contenu in famille_panda_df.iterrows():
    print(f'Voici le panda {idx}')
    print(contenu)
    print("----------------")

Voici le panda maman
pattes    100.0
poil        5.0
queue      20.0
ventre     80.0
Name: maman, dtype: float64
----------------
Voici le panda bebe
pattes    50.0
poil       2.5
queue     10.0
ventre    40.0
Name: bebe, dtype: float64
----------------
Voici le panda papa
pattes    110.0
poil        6.0
queue      22.0
ventre     80.0
Name: papa, dtype: float64
----------------


In [15]:
# Acceder auu papa panda
famille_panda_df.iloc[2]
# ou
famille_panda_df.loc['papa']

pattes    110.0
poil        6.0
queue      22.0
ventre     80.0
Name: papa, dtype: float64

In [ ]:
## 